### ISSUE TITLE
Plugin: Kalenderimport

### ISSUE THREAD

**Issue by xwolfde** [Piratenpartei/WebsiteRelaunch2017#10]
Wie brauchen eine Lösung um die verschiedenen Termine der Piraten aus den unterschiedlichen Kalendern zusammenzuführen und in die Website einzublenden.
Auch hierbei soll es ein Merge geben können, dass Termine verschiedener Kalender in einem Stream erscheinen können.

**Comment by patrickschiffer** [comment]
Ich wäre dafür, unter dem Navigationspunkt "Presse" auch unseren Pressekalender einzubinden: https://calendar.google.com/calendar/embed?src=bupress%40ag-technik.de

**Comment by xwolfde** [comment]
Ja, aber nicht so direkt, sondern via Plugin. Gibt es von dort eine ICS-URL?

**Comment by xwolfde** [comment]
https://85ideas.com/plugins/best-free-wordpress-google-calendar-plugins/
https://de.wordpress.org/plugins/google-calendar-events/screenshots/

testen

**Comment by xwolfde** [comment]
Haben wir . ICS Quellen müssen gesammelt werden. Dann können wir auch anzeigen. Bis dahin wird der Wikikalender angezeigt
