### ISSUE TITLE
Kategorien

### ISSUE THREAD

**Issue by xwolfde** [Piratenpartei/WebsiteRelaunch2017#11]
Wir haben eine große Zahl an teilweise redundanten Kategorien auf der bestehenden Website für Artikel. Diese sollten verschlankt werden und die Redundanzen abgeschafft werden.

Welche Kategorien sollten wir nach dem Relaunch haben?

**Comment by patrickschiffer** [comment]
Pad für die Kategorien: https://pr02.piratenpad.de/schlagworte

**Comment by xwolfde** [comment]
Die Kategorien müssen usable und verständlich sein. Das bedeutet, dass es maximal 7 Elemente pro Ebene sein sollten.

Alle Politikfelder als Kategorien einstellen ist da sinnlos und macht es unübersichtlich.
Es ist für mich auch nicht sinnvoll Kategorien abhängig vom Art des Typs eines Beitrags zu machen. Denn Kategorien sind auf den Inhalt bezogen nicht aufd en Verbreitungsweg oder die Darstellung.

Wenn ich es richtig sehe, hat Sperling bereits folgende Oberkategorien erarbeitet:

- Familie, Gesellschaft & Grundeinkommen
- Sicherheit, Justiz & Bürgerrechte
- Umwelt, Energie & Nachhaltigkeit
- Digitalisierung, Datenschutz & Privatspäre
- Staat, Demokratie & Transparenz
- Wirtschaft, Finanzen & Umverteilung
- Bildung, Kultur & Teilhabe


Das finde ich schonmal einen guten Ansatz.

**Comment by xwolfde** [comment]
Aus Besprechung vom 25.1.

- Vorschlag 1: (Noch in Arbeit): https://pr02.piratenpad.de/schlagworte
- Vorschlag 2: Von den 3 beschlossenen Oberpunkten ausgehen und nach unten gliedern: 
- Vorschlag 3: Strikt nach dem vorhandenen Programm gehen    
- Vorschlag 4: Es gab mal 7 Oberpunkte; Wird nachrecherchiert

**Comment by xwolfde** [comment]
Hier wurde noch was schönes gemacht: 
https://bubbl.us/Mzg0MzM3OC83NjIxNDA3LzYwZDJlYjZiY2RiOTYyNzk5NmRkZTQ3NDc1OWE1ZThi-X

**Comment by SperlingFP** [comment]
Die idee war, unter dem Hauptpunkt "Politisches Programm" die 7 Unterpunkte 

**Familie, Gesellschaft & Grundeinkommen
Sicherheit, Justiz & Bürgerrechte
Umwelt, Energie & Nachhaltigkeit
Digitalisierung, Datenschutz & Privatspäre
Staat, Demokratie & Transparenz
Wirtschaft, Finanzen & Umverteilung
Bildung, Kultur & Teilhabe**

Es geht darum, die Politikbereiche mit einem werbewirksamen Begriff zu verbinden der auch aussagt worum es da vor allem geht.

Unter dem Hauptpunkt "Unsere Strutkuren (oder auch "Wir die Partei" oder so) würde ich dann das folgende einordnen(strukturkrm, Verwaltung etc.):

**Die Bundespartei 
Unsere Verbände (LB, BzV, KV)
Parteitage und Konferenzen /Marina, PirateSeCon etc.)
Daten und Fakten**


Unter dem Hauptpunkt "Unsere Aktionen" würde ich laufende und auch erfolgreich gelaufene Aktionen präsentieren - Mit und ohne Bündnispartner, Bundesweit, Landesweit, Lokal - alles! Thematisch sortieren würd eich sie nicht, es sei den wir wollen mehr als 5 Parallel haben - und wichtig: Ein Archiv der gelaufene Sachen! Unterpunkte:

**Aktiv für Thema 1
Aktiv für Thema 2
Aktiv für Thema 3
Aktiv gegen Nazis
Archiv**

Unter dem Hauptpunkt "Sich beteiligen" gehören für mich drei Dinge:

**Als unser Bündnispartner
Als Freund und Helfer
Als Mitglied an Bord kommen
Finanziell und Materiell unterstützen**

Letzter Hauptpunkt: "Presse & Social Media": Hier gehören der Teil für Journalisten rein und der SocialMedia Bereich mit Livefeeds (twitter etc.), Adressen/Accountsnamen (mail, twitter, Facebook etc), Flaschenpost und Krähennest und so weiter -  von allen Einheiten, nicht nur vom Bund

**Comment by xwolfde** [comment]
geklärt, siehe arbeitspad
