### ISSUE TITLE
Aaika Theme

### ISSUE THREAD

**Issue by xwolfde** [Piratenpartei/WebsiteRelaunch2017#2]
Konfiguration des Aaika Themes derzeit schwierig, da noch nicht bei Aktivierung compatibel mit WP4.7
Case ist offen: https://themeforest.net/item/aaika-multipurpose-wordpress-theme/10103467/comments?page=26&filter=all#comment_15076892

**Comment by xwolfde** [comment]
Anmerkung: In der letzten Besprechung am 20.12. haben wir uns für Aaika entschieden wegen des vorhandenen Know-Hows. 

Aaika wurde bereits auf die Instanzen test.*  und beta.*   installiert (vor dem Crash).

**Comment by xwolfde** [comment]
Rückmeldung da, es soll eine EInstellung in der Config helfen. Werde das testen

**Comment by mikalehmann** [comment]
Kann geschlossen werden, oder?

**Comment by xwolfde** [comment]
Jupp ;)
